name: Fitya Dev Start Request

on:
  workflow_dispatch:
    inputs:
      lifetime:
        description: Dev Env Lifetime
        type: choice
        options: 
        - 60
        - 120
        - 180

jobs:
  start-request:
    uses: ./.github/workflows/irchad-dev-start-request.yml
    with:
      lifetime: ${{ github.event.inputs.lifetime }}
