name: Fitya Dev Start Request

on:
  workflow_dispatch:
    inputs:
      lifetime:
        description: Dev Env Lifetime (Minutes)
        type: choice
        required: true
        default: '60'
        options: 
        - 60
        - 90
        - 120
        - 180

jobs:
  start-request:
    uses: ./.github/workflows/irchad-dev-start-request.yml
    with:
      lifetime: ${{ fromJSON(inputs.lifetime) }}
