name: Irchad Dev Request Start

on:
  workflow_call:
    inputs:
      lifetime:
        type: number
        required: true

jobs:
  request-start:
    runs-on: ubuntu-latest
    steps:
      - name: Init Dev Request Start
        env:
          AWS_DEV_REQUEST_LIFETIME: ${{ inputs.lifetime }}
        run: |
          AWS_DEV_REQUEST_START=$(date +'%Y-%m-%d %H:%M:%S')
          AWS_DEV_REQUEST_END=$(date "$AWS_DEV_REQUEST_START $AWS_DEV_REQUEST_LIFETIME hours" +'%Y-%m-%d %H:%M:%S')
          
          echo AWS_DEV_REQUEST_START=\"$AWS_DEV_REQUEST_START\" > aws_dev_request.txt
          echo AWS_DEV_REQUEST_LIFETIME=\"$AWS_DEV_REQUEST_LIFETIME\" >> aws_dev_request.txt
          echo AWS_DEV_REQUEST_END=\"$AWS_DEV_REQUEST_END\" >> aws_dev_request.txt
          
          cat aws_dev_request.txt

      - name: Upload Dev Request Start File
        uses: actions/upload-artifact@v4
        with:
          name: aws-dev-request-start-artifact
          path: aws_dev_request_start.txt
